[package]
name = "linera-sdk-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
linera-views-derive = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["parsing"] }
